### ISSUE TITLE
parsing filenames with non-ascii characters

### ISSUE THREAD

**Issue by Battleman** [gcmalloc/epfl-moodle#7]
At EPFL, many courses are taught in french, resulting in filenames with non-ascii characters (such as é,à,ê,è,...). It currently results in the following error : 
_UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 25: ordinal not in range(128)_ (example for filename __Introduction, e-mail forgé__).
Below the traceback : 

    Traceback (most recent call last):
      File "/usr/local/bin/moodle", line 4, in <module>
        __import__('pkg_resources').run_script('epfl-moodle==0.5.0', 'moodle')
      File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 742, in run_script
        self.require(requires)[0].run_script(script_name, ns)
      File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1510, in run_script
        exec(script_code, namespace, namespace)
      File "/usr/local/lib/python2.7/dist-packages/epfl_moodle-0.5.0-py2.7.egg/EGG-INFO/scripts/moodle", line 179, in <module>
    
    File "/usr/local/lib/python2.7/dist-packages/epfl_moodle-0.5.0-py2.7.egg/EGG-INFO/scripts/moodle", line 165, in main
    File "/usr/local/lib/python2.7/dist-packages/epfl_moodle-0.5.0-py2.7.egg/EGG-INFO/scripts/moodle", line 72, in course_download
    
      File "build/bdist.linux-x86_64/egg/epfl_moodle/moodle.py", line 26, in __str__
    UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 25: ordinal not in range(128)

**Comment by antoinealb** [comment]
Could you try installing the software with Python 3 ? It has better support for unicode, and this program is compatible with both Python 3 and 2.7 (I am running it under Python 3.6 personally).

**Comment by Battleman** [comment]
a simple `python3 setup.py install` completes but does not work, probably because of the previous install. How do I remove the 2.7 installation ?

**Comment by antoinealb** [comment]
You can check which version you are using by running `which moodle`.

To uninstall it you can run `pip uninstall epfl-moodle`.

**Comment by Battleman** [comment]
No more ascii problem with python 3.6. Note that I had to install `keyrings.alt` package (with pip) to have access to the keyring.
Thanks for the help

**Comment by antoinealb** [comment]
Interesting. Which platform are you using ? I am on OSX and it worked with `keyrings.alt`.

**Comment by Battleman** [comment]
Debian stretch 4.12.0-1-amd64. 
It too works with `keyrings.alt`, but it wasn't installed, so I got the following error
```
Traceback (most recent call last):
  File "/home/battleman/Programs/anaconda3/bin/moodle", line 4, in <module>
    __import__('pkg_resources').run_script('epfl-moodle==0.5.0', 'moodle')
  File "/home/battleman/Programs/anaconda3/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 744, in run_script
  File "/home/battleman/Programs/anaconda3/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 1506, in run_script
  File "/home/battleman/Programs/anaconda3/lib/python3.6/site-packages/epfl_moodle-0.5.0-py3.6.egg/EGG-INFO/scripts/moodle", line 179, in <module>
  File "/home/battleman/Programs/anaconda3/lib/python3.6/site-packages/epfl_moodle-0.5.0-py3.6.egg/EGG-INFO/scripts/moodle", line 121, in main
  File "/home/battleman/Programs/anaconda3/lib/python3.6/site-packages/keyring-10.4.0-py3.6.egg/keyring/core.py", line 41, in get_password
  File "/home/battleman/Programs/anaconda3/lib/python3.6/site-packages/keyring-10.4.0-py3.6.egg/keyring/backends/fail.py", line 23, in get_password
RuntimeError: No recommended backend was available. Install the keyrings.alt package if you want to use the non-recommended backends. See README.rst for details.
```

After installing this package (with aptitude and pip) it worked flawlessly.

**Comment by antoinealb** [comment]
Okay, apparently it depends on your desktop environment (https://github.com/jaraco/keyring/blob/master/README.rst#what-is-python-keyring-lib). I will add a note to the README.
